ALTER TABLE tasks ADD COLUMN planned_date TEXT;
CREATE INDEX tasks_owner_due_idx ON tasks(owner_id,due_date) WHERE trashed_at IS NULL;
CREATE INDEX tasks_owner_planned_idx ON tasks(owner_id,planned_date) WHERE trashed_at IS NULL;
CREATE INDEX notes_owner_journal_idx ON notes(owner_id,daily_date) WHERE trashed_at IS NULL;
CREATE TABLE calendar_events(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',start_date TEXT NOT NULL,end_date TEXT NOT NULL,recurring INTEGER NOT NULL DEFAULT 0,data TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1,trashed_at INTEGER,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE INDEX calendar_events_range_idx ON calendar_events(owner_id,start_date,end_date) WHERE trashed_at IS NULL;
CREATE INDEX calendar_events_repeating_idx ON calendar_events(owner_id,recurring) WHERE trashed_at IS NULL;
CREATE INDEX calendar_events_search_order_idx ON calendar_events(owner_id,updated_at DESC,id) WHERE trashed_at IS NULL;
CREATE INDEX calendar_events_trash_idx ON calendar_events(owner_id,trashed_at) WHERE trashed_at IS NOT NULL;
CREATE TABLE calendar_exceptions(event_id TEXT NOT NULL REFERENCES calendar_events(id) ON DELETE CASCADE,occurrence TEXT NOT NULL,override_id TEXT REFERENCES calendar_events(id) ON DELETE SET NULL,PRIMARY KEY(event_id,occurrence));
CREATE TABLE event_tags(event_id TEXT NOT NULL REFERENCES calendar_events(id) ON DELETE CASCADE,tag_id TEXT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,PRIMARY KEY(event_id,tag_id));
CREATE INDEX event_tags_reverse_idx ON event_tags(tag_id,event_id);
CREATE TABLE calendar_links(event_id TEXT NOT NULL REFERENCES calendar_events(id) ON DELETE CASCADE,type TEXT NOT NULL,item_id TEXT NOT NULL,PRIMARY KEY(event_id,type,item_id));
CREATE INDEX calendar_links_target_idx ON calendar_links(type,item_id);
CREATE TABLE calendar_task_reminders(task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,timezone TEXT NOT NULL,field TEXT NOT NULL,offsets TEXT NOT NULL,PRIMARY KEY(task_id,field));
CREATE TABLE calendar_reminders(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE,source_type TEXT NOT NULL,source_id TEXT NOT NULL,occurrence TEXT NOT NULL,revision INTEGER NOT NULL,title TEXT NOT NULL,starts_at INTEGER NOT NULL,scheduled_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,state TEXT NOT NULL DEFAULT 'queued',dismissed INTEGER NOT NULL DEFAULT 0,UNIQUE(source_type,source_id,occurrence,revision,scheduled_at));
CREATE INDEX calendar_reminders_due_idx ON calendar_reminders(state,scheduled_at);
CREATE INDEX calendar_reminders_owner_idx ON calendar_reminders(owner_id,scheduled_at);
CREATE TABLE push_subscriptions(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE,session_id TEXT NOT NULL REFERENCES session(id) ON DELETE CASCADE,endpoint_hash TEXT NOT NULL UNIQUE,data BLOB NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE calendar_deliveries(reminder_id TEXT NOT NULL REFERENCES calendar_reminders(id) ON DELETE CASCADE,subscription_id TEXT NOT NULL REFERENCES push_subscriptions(id) ON DELETE CASCADE,state TEXT NOT NULL DEFAULT 'queued',attempts INTEGER NOT NULL DEFAULT 0,available_at INTEGER NOT NULL,lease_until INTEGER,PRIMARY KEY(reminder_id,subscription_id));
CREATE TABLE calendar_secrets(id TEXT PRIMARY KEY,data BLOB NOT NULL);
CREATE VIRTUAL TABLE events_fts USING fts5(title,description,content=calendar_events,content_rowid=rowid);
CREATE TRIGGER events_ai AFTER INSERT ON calendar_events BEGIN INSERT INTO events_fts(rowid,title,description) VALUES(new.rowid,new.title,new.description); END;
CREATE TRIGGER events_ad AFTER DELETE ON calendar_events BEGIN INSERT INTO events_fts(events_fts,rowid,title,description) VALUES('delete',old.rowid,old.title,old.description); END;
CREATE TRIGGER events_au AFTER UPDATE ON calendar_events BEGIN INSERT INTO events_fts(events_fts,rowid,title,description) VALUES('delete',old.rowid,old.title,old.description); INSERT INTO events_fts(rowid,title,description) VALUES(new.rowid,new.title,new.description); END;
